source 'https://rubygems.org'

gemspec

gem 'bundler'
gem 'discogs-wrapper'
gem 'faraday'
gem 'http'
gem 'io-dispatcher', github: 'jslabovitz/io-dispatcher'
gem 'json'
gem 'mime-types'
gem 'minitest'
gem 'minitest-power_assert'
gem 'mpv_client', github: 'jslabovitz/mpv_client'
gem 'prawn'
gem 'rake'
gem 'run-command', github: 'jslabovitz/run-command'
gem 'set_params'
gem 'simple-command', github: 'jslabovitz/simple-command'
gem 'simple-group', github: 'jslabovitz/simple-group'
gem 'simple-printer', github: 'jslabovitz/simple-printer'
gem 'sixarm_ruby_unaccent'
gem 'tty-config'
gem 'tty-prompt'